# Generated by Django 4.1 on 2022-08-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_club_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.CharField(default='abcd', max_length=100),
            preserve_default=False,
        ),
    ]
