# Generated by Django 4.1 on 2022-08-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
