# Generated by Django 4.1.2 on 2022-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clubId", models.IntegerField()),
                ("postId", models.IntegerField()),
                ("commented_by", models.CharField(max_length=50)),
                ("body", models.TextField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
