# Generated by Django 4.1.2 on 2022-11-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="webpost", to="api.user"
            ),
        ),
    ]
