# Generated by Django 4.1.2 on 2022-11-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_post_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
