# Generated by Django 4.1.2 on 2022-11-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_body_comment_comment_remove_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(blank=True, to="api.user"),
        ),
    ]
